export default class TypeAction {

    static LISTAR_TAG = "LISTAR_TAG";
    static LISTAR_ARTICLES = "LISTAR_ARTICLES";    
    static LISTAR_CATEGORY = "LISTAR_CATEGORY";
    static FIND_ID = "FIND_ID";
    static ADD_TAG = "ADD_TAG";
    static CLEAN_FORM = "CLEAN_FORM";
    static MODIFIED_VALUE_FIELD = "MODIFIED_VALUE_FIELD";
    static USER_AUTHENTICATED = "USER_AUTHENTICATED";
    static ADD_CATEGORY = "ADD_CATEGORY";
    static ADD_TAG_IN_ARTICLE = "ADD_TAG_IN_ARTICLE";
    static REMOVE_TAG = "REMOVE_TAG";
    static REMOVE_CATEGORY = "REMOVE_CATEGORY"
}